#!/bin/sh
# Mobile Broadband Startup Service script 
# USAGE: start|stop|status
#
### BEGIN INIT INFO 
# Provides: Automatic mobile broadband connection on boot
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Should-Start: $network
# Should-Stop: $network
# Default-Start: 3 4 5 
# Default-Stop: 0 1 6 
# Short-Description: Autoconnect 4G GSM
### END INIT INFO

NAME="mobile-broadband-connect"
DESC="Autoconnect 3G/4G GSM USB modem at startup"

test -x $DAEMON || exit 0

case "$1" in
    start)
       echo "Starting Mobile Broadband Connection."

       while true; do
          # Check and see if device is detected
          LC_ALL=C nmcli -t -f TYPE,STATE dev | grep -q "^gsm:disconnected$"
          if [ $? -eq 0 ]; then
             # Found it!
             break
          else
             # No GSM detected yet, sleeping for a second
             sleep 1
          fi
       done

       # Once GSM modem detected, connect
       nmcli -t con up id gsmmodem
    ;;
    stop)
       echo "Stopping Mobile Broadband Connection."
       nmcli -t con down id gsmmodem
    ;;
    status)
       # Check to see if the process is running with nmcli
       nmcli -p dev
    ;;
    
    *)
       echo "Mobile Broadband Autostart Service"
       echo $"Usage: $0 {start|stop|status}"
       exit 1
esac
exit 0
